[package]
name = "tdy"
version = "0.0.7"
edition = "2024"
authors = ["Oto Brglez <otobrglez@gmail.com>"]

[dependencies]
chrono = "0.4.44"
clap = { version = "4.6.1", features = ["derive", "env"] }
env_logger = "0.11.10"
log = "0.4.29"
minijinja = "2.19.0"
tempfile = "3.27.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
