[package]
name = "tdy"
version = "0.0.1"
edition = "2021"
authors = ["Oto Brglez <otobrglez@gmail.com>"]

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.2", features = ["derive", "debug"] }
minijinja = "0.34.0"
tempfile = "3.6.0"
