[package]
name = "tdy"
version = "0.0.3"
edition = "2024"
authors = ["Oto Brglez <otobrglez@gmail.com>"]

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.46", features = ["derive", "env"] }
minijinja = "0.34.0"
